### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NeginZarbakhsh** [facebookincubator/mapillary-python-sdk#150]
**Describe the bug**
xtile = int(math.floor((x + EPSILON) * Z2))
ValueError: cannot convert float NaN to integer

**To Reproduce**
This is the code I am using to collect th close-to images to a specific coordinates:
for index, row in enumerate(df.iterrows()):
  coordinates_to_image_id_dict: dict = {}
  latitude, longitude = dict(row[1])['LATITUDE'], dict(row[1])['LONGITUDE'] 
  coordinates_to_image_id_dict['lat'] = latitude
  coordinates_to_image_id_dict['lng'] = longitude
  try:
      data= mly.get_image_close_to(
          latitude=latitude,
          longitude=longitude,
          radius=35,
          image_type="flat",
          min_captured_at="2016-01-01"
      ).to_dict()

  except AttributeError:
      print('AttributeError occurred')
      data = {}
      
  print(data)  
  print('latitude and longitude:', latitude, longitude)

**Expected behavior**
if math.isnan(x):
    # handle NaN case here
else:
    xtile = int(math.floor((x + EPSILON) * Z2))

**Screenshots**
latitude and longitude: 51.9326934493218 -8.05201349824569
Requesting GET to https://tiles.mapillary.com/maps/vtp/mly1_public/2/14/7892/5318/?access_token=MLY%???
Response 200 OK received in 78ms
{'type': 'FeatureCollection', 'features': []}

latitude and longitude: 53.2429118794892 -6.58873419758931
Traceback (most recent call last):
  File "Data_collection_json_metadata.py", line 39, in <module>
    min_captured_at="2016-01-01"
  File "/home/peoplexxx/.local/lib/python3.7/site-packages/mapillary/utils/auth.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/people/xx/.local/lib/python3.7/site-packages/mapillary/interface.py", line 116, in get_image_close_to
    kwargs=kwargs,
  File "/home/people/xx/.local/lib/python3.7/site-packages/mapillary/controller/image.py", line 110, in get_image_close_to_controller
    latitude=latitude,
  File "/home/people/xxx/.local/lib/python3.7/site-packages/mapillary/models/api/vector_tiles.py", line 123, in fetch_layer
    tile=mercantile.tile(lng=longitude, lat=latitude, zoom=zoom),
  File "/home/people/xxxx/.local/lib/python3.7/site-packages/mercantile/__init__.py", line 426, in tile
    xtile = int(math.floor((x + EPSILON) * Z2))
ValueError: cannot convert float NaN to integer

**Comment by sam7676** [comment]
Reproducible through
``` python
mapillary.interface.get_image_close_to(
        latitude=50,  # any reasonable number
        longitude=np.nan,
        radius=35,
        image_type="flat",
        min_captured_at="2016-01-01",
    )
```
Can't extract OP's true inputs but presumably np.nan from the dataframe, the error was raised before latitude/longitude were displayed. An input of NaN as lat/lon should raise an error anyway, I think this is expected behaviour from the SDK (/mercantile).
